### ISSUE TITLE
Inline form layout on /status_graph.php

### ISSUE THREAD

**Issue by SjonHortensius** [SjonHortensius/pfsense#166]
![screenshot-11080](https://cloud.githubusercontent.com/assets/1684987/7473768/bd3315a6-f33d-11e4-85cd-d225e3e2572f.png)

I've tried this but it leaves the labels, not sure what the correct method is

``` css
.form-inline input, 
.form-inline select
{
   width: 150px;
}
```
